### ISSUE TITLE
server.close() implementation

### ISSUE THREAD

**Issue by Fi1osof** [warrenday/cypress-graphql-mock-network#3]
Good day!

[msw](https://github.com/mswjs/msw) have server.close() method.

```js
// Disable API mocking after the tests are done.
afterAll(() => server.close())
```

Can i invoke server.close() with cypress-graphql-mock-network? 
Now, when i run more that one test, mock server works for other tests too.

**Comment by warrenday** [comment]
Sorry for the very late reply, this has been implemented with this PR
https://github.com/warrenday/cypress-graphql-mock-network/commit/ec1e1518e3f9ef31599eb420ca271c55af03bb97

You can now use "mockNetworkStop" to prevent later tests being mocked.

**Comment by Fi1osof** [comment]
@warrenday , thanks!
