### ISSUE TITLE
How to use custom scalars

### ISSUE THREAD

**Issue by luisrudge** [warrenday/cypress-graphql-mock-network#4]
I have a schema with this custom scalar:

```
scalar DateTime
```

When I run the tests, I get this error: `"No mock defined for type "DateTime"`.
My current workaround is converting that to strings like this:

```ts
cy.mockNetwork({
  schema: schema.replace('DateTime', 'String'),
});
```

**Comment by luisrudge** [comment]
ping @warrenday

**Comment by warrenday** [comment]
Hey, I should include this on the main readme. To use custom scalars you need to load them into mock network so the mock GraphQL server running on the client is aware of how to handle them.

What I usually do is create a custom command which applies any "setup" in one place. So here in a recent project, I have the following inside `support/commands.ts`

```ts
import { mocks as scalarMocks } from 'graphql-scalars';

// Maybe you have some sensible default mocks you always want in every test
export const globalDefaultMocks = {
  Query: () => ({
    getAccount: () => ({
      id: 'a4c49b77-aaba-499b-81aa-eb230f2a73c6',
    }),
  }),
};

const setupMockNetwork = () => {
  cy.readFile('./graphql.schema.json').then(schema => {
    cy.mockNetwork({
      schema,
      mocks: {
        ...scalarMocks,
        ...globalMocks,
      },
    });
  });
};
Cypress.Commands.add('setupMockNetwork', setupMockNetwork);
```

Then later in tests, you can just do

```ts
describe('Account - Billing', function() {
  beforeEach(() => {
    cy.setupMockNetwork();
    cy.mockNetworkAdd({
      Mutation: () => ({
        createSubscription: () => ({
          planId: '23234',
          status: 'active',
        }),
      }),
    });
  });

  it('asserts some stuff', () => {
    cy.visit('http://localhost:3000/account/billing');

    // Add more mocks or run some tests here
  })
});
```

If you are using custom mocks you have written yourself, or from a different lib, you just need to define those mocks in your schema like.

```ts
cy.mockNetwork({
  schema,
  mocks: {
    Date: (root, args) => new Date(),
    JSON: (root, args) => '{}'
  },
});
```

**Comment by luisrudge** [comment]
@warrenday thanks for the answer. The issue with that approach is that all my mocked types (dates or JSONs) will be the same, right? I won't be able to load them from my fixture. For example, I have a fixture like this:

```json
{
  "product": {
    "id": "83183027-1f1b-4ff2-98b1-85439c8f1edd",
    "created": "2020-11-05T16:27:41.589000+00:00",
    "jsonThing": "{\"test\": true}"
  }
}
```

When I add a DateTime or JSONString mock, it basically forces me to use a single value, not being able to check if I'm loading from the correct property, right?

```js
cy.mockNetwork({
  schema,
  mocks: {
    DateTime: () => '2021-01-01',
    JSONString: () => JSON.stringify({ fromTest: true }),
  },
});
```

That means that all my DateTime types will be the same and all my JSONString types will be the same as well. When I `console.log` the `root` and `args`, I get undefined, so I can't use that to figure out where to pull the data from either.

**Comment by warrenday** [comment]
Those mocks just need to exist to prevent GraphQL from complaining that they are missing. Then you can apply dynamic mocks through the mocking of specific queries/mutations. These resolvers should then take precedent. 

Here for example `args` will be populated inside the getProduct resolver, so you can provide different responses given different input.

```ts
cy.mockNetwork({
  schema,
  mocks: {
    DateTime: () => '2021-01-01',
    JSONString: () => JSON.stringify({ fromTest: true }),
    Query: () => ({
      getProduct: (root, args) => ({
        "id": "83183027-1f1b-4ff2-98b1-85439c8f1edd",
        "created": "2020-11-05T16:27:41.589000+00:00",
        "jsonThing": "{\"test\": true}"
      })
    })
  },
});
```

I confused things above by including the `root`, `arg` parameters in the scalar resolvers. (sorry about that).

**Comment by luisrudge** [comment]
something feels off here, maybe I'm missing something, but I'm getting lots of random values instead of my mocked values. For example:

```tsx
beforeEach(() => {
  cy.readFile('src/graphql/__schema.graphql').then((schema: string) => {
    cy.mockNetwork({
      schema,
      mocks: {
        DateTime: () => '2021-01-01',
        JSONString: () => JSON.stringify({ fromTest: true }),
        Query: () => ({
          products: (_: unknown, p: QueryProductsArgs) => {
            expect(p.limit).to.be.eq(10);
            expect(p.offset).to.be.eq(0);
            return listResult;
          },
          product: (_: unknown, p: QueryProductArgs) => {
            expect(p.id).to.be.be.eq(singleResult.data.product.id);
            return singleResult;
          },
        }),
      },
    });
  });
});
```

When I console.log my component, it shows me lots of random 'Hello World' strings:
![image](https://user-images.githubusercontent.com/941075/119171880-8b6dd580-ba3b-11eb-9570-97f97733926e.png)

But this has nothing to do with my fixture files:
![image](https://user-images.githubusercontent.com/941075/119171913-9c1e4b80-ba3b-11eb-8938-feeeccdd3eff.png)

**Comment by luisrudge** [comment]
Ah, that makes perfect sense. Thanks!
